version: '3.8'

services:
    web:
        container_name: drf_mailing
        build: .
        command: > 
            bash -c "python manage.py migrate --run-syncdb
            && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./:/usr/src/app/
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        container_name: DB
        image: postgres:12.0-alpine
        volumes:
            - postgres_volume:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        env_file:
            - ./.env
    redis:
        container_name: redis
        image: redis:7.0.4
        restart: always
        ports:
            - 6379:6379
    celery:
        container_name: celery
        restart: always
        build: .
        command: celery -A drf_mailing worker -l info -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
                        
        volumes:
            - ./:/usr/src/app/
        depends_on:
            - db
            - redis
            - web
    flower:
        container_name: flower
        build: .
        command: celery -A drf_mailing flower -l info
        ports:
            - 5555:5555
        depends_on:
            - celery
            - redis
volumes:
    postgres_volume: